# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/datamodel/crawler/innotree/hotnews/sort

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/datamodel/crawler/innotree/hotnews/sort

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/datamodel/crawler/innotree/hotnews/sort/CMakeFiles /data/datamodel/crawler/innotree/hotnews/sort/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/datamodel/crawler/innotree/hotnews/sort/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SortNews

# Build rule for target.
SortNews: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SortNews
.PHONY : SortNews

# fast build rule for target.
SortNews/fast:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/build
.PHONY : SortNews/fast

article.o: article.cpp.o

.PHONY : article.o

# target to build an object file
article.cpp.o:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/article.cpp.o
.PHONY : article.cpp.o

article.i: article.cpp.i

.PHONY : article.i

# target to preprocess a source file
article.cpp.i:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/article.cpp.i
.PHONY : article.cpp.i

article.s: article.cpp.s

.PHONY : article.s

# target to generate assembly for a file
article.cpp.s:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/article.cpp.s
.PHONY : article.cpp.s

article_spool.o: article_spool.cpp.o

.PHONY : article_spool.o

# target to build an object file
article_spool.cpp.o:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/article_spool.cpp.o
.PHONY : article_spool.cpp.o

article_spool.i: article_spool.cpp.i

.PHONY : article_spool.i

# target to preprocess a source file
article_spool.cpp.i:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/article_spool.cpp.i
.PHONY : article_spool.cpp.i

article_spool.s: article_spool.cpp.s

.PHONY : article_spool.s

# target to generate assembly for a file
article_spool.cpp.s:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/article_spool.cpp.s
.PHONY : article_spool.cpp.s

extractTerms/Utility.o: extractTerms/Utility.cpp.o

.PHONY : extractTerms/Utility.o

# target to build an object file
extractTerms/Utility.cpp.o:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/extractTerms/Utility.cpp.o
.PHONY : extractTerms/Utility.cpp.o

extractTerms/Utility.i: extractTerms/Utility.cpp.i

.PHONY : extractTerms/Utility.i

# target to preprocess a source file
extractTerms/Utility.cpp.i:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/extractTerms/Utility.cpp.i
.PHONY : extractTerms/Utility.cpp.i

extractTerms/Utility.s: extractTerms/Utility.cpp.s

.PHONY : extractTerms/Utility.s

# target to generate assembly for a file
extractTerms/Utility.cpp.s:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/extractTerms/Utility.cpp.s
.PHONY : extractTerms/Utility.cpp.s

extractTerms/countWord.o: extractTerms/countWord.cpp.o

.PHONY : extractTerms/countWord.o

# target to build an object file
extractTerms/countWord.cpp.o:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/extractTerms/countWord.cpp.o
.PHONY : extractTerms/countWord.cpp.o

extractTerms/countWord.i: extractTerms/countWord.cpp.i

.PHONY : extractTerms/countWord.i

# target to preprocess a source file
extractTerms/countWord.cpp.i:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/extractTerms/countWord.cpp.i
.PHONY : extractTerms/countWord.cpp.i

extractTerms/countWord.s: extractTerms/countWord.cpp.s

.PHONY : extractTerms/countWord.s

# target to generate assembly for a file
extractTerms/countWord.cpp.s:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/extractTerms/countWord.cpp.s
.PHONY : extractTerms/countWord.cpp.s

extractTerms/fileOperation.o: extractTerms/fileOperation.cpp.o

.PHONY : extractTerms/fileOperation.o

# target to build an object file
extractTerms/fileOperation.cpp.o:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/extractTerms/fileOperation.cpp.o
.PHONY : extractTerms/fileOperation.cpp.o

extractTerms/fileOperation.i: extractTerms/fileOperation.cpp.i

.PHONY : extractTerms/fileOperation.i

# target to preprocess a source file
extractTerms/fileOperation.cpp.i:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/extractTerms/fileOperation.cpp.i
.PHONY : extractTerms/fileOperation.cpp.i

extractTerms/fileOperation.s: extractTerms/fileOperation.cpp.s

.PHONY : extractTerms/fileOperation.s

# target to generate assembly for a file
extractTerms/fileOperation.cpp.s:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/extractTerms/fileOperation.cpp.s
.PHONY : extractTerms/fileOperation.cpp.s

extractTerms/searchTerm.o: extractTerms/searchTerm.cpp.o

.PHONY : extractTerms/searchTerm.o

# target to build an object file
extractTerms/searchTerm.cpp.o:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/extractTerms/searchTerm.cpp.o
.PHONY : extractTerms/searchTerm.cpp.o

extractTerms/searchTerm.i: extractTerms/searchTerm.cpp.i

.PHONY : extractTerms/searchTerm.i

# target to preprocess a source file
extractTerms/searchTerm.cpp.i:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/extractTerms/searchTerm.cpp.i
.PHONY : extractTerms/searchTerm.cpp.i

extractTerms/searchTerm.s: extractTerms/searchTerm.cpp.s

.PHONY : extractTerms/searchTerm.s

# target to generate assembly for a file
extractTerms/searchTerm.cpp.s:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/extractTerms/searchTerm.cpp.s
.PHONY : extractTerms/searchTerm.cpp.s

extractTerms/simpleDic.o: extractTerms/simpleDic.cpp.o

.PHONY : extractTerms/simpleDic.o

# target to build an object file
extractTerms/simpleDic.cpp.o:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/extractTerms/simpleDic.cpp.o
.PHONY : extractTerms/simpleDic.cpp.o

extractTerms/simpleDic.i: extractTerms/simpleDic.cpp.i

.PHONY : extractTerms/simpleDic.i

# target to preprocess a source file
extractTerms/simpleDic.cpp.i:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/extractTerms/simpleDic.cpp.i
.PHONY : extractTerms/simpleDic.cpp.i

extractTerms/simpleDic.s: extractTerms/simpleDic.cpp.s

.PHONY : extractTerms/simpleDic.s

# target to generate assembly for a file
extractTerms/simpleDic.cpp.s:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/extractTerms/simpleDic.cpp.s
.PHONY : extractTerms/simpleDic.cpp.s

extractTerms/tl_codetbl.o: extractTerms/tl_codetbl.cpp.o

.PHONY : extractTerms/tl_codetbl.o

# target to build an object file
extractTerms/tl_codetbl.cpp.o:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/extractTerms/tl_codetbl.cpp.o
.PHONY : extractTerms/tl_codetbl.cpp.o

extractTerms/tl_codetbl.i: extractTerms/tl_codetbl.cpp.i

.PHONY : extractTerms/tl_codetbl.i

# target to preprocess a source file
extractTerms/tl_codetbl.cpp.i:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/extractTerms/tl_codetbl.cpp.i
.PHONY : extractTerms/tl_codetbl.cpp.i

extractTerms/tl_codetbl.s: extractTerms/tl_codetbl.cpp.s

.PHONY : extractTerms/tl_codetbl.s

# target to generate assembly for a file
extractTerms/tl_codetbl.cpp.s:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/extractTerms/tl_codetbl.cpp.s
.PHONY : extractTerms/tl_codetbl.cpp.s

heap_util.o: heap_util.cpp.o

.PHONY : heap_util.o

# target to build an object file
heap_util.cpp.o:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/heap_util.cpp.o
.PHONY : heap_util.cpp.o

heap_util.i: heap_util.cpp.i

.PHONY : heap_util.i

# target to preprocess a source file
heap_util.cpp.i:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/heap_util.cpp.i
.PHONY : heap_util.cpp.i

heap_util.s: heap_util.cpp.s

.PHONY : heap_util.s

# target to generate assembly for a file
heap_util.cpp.s:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/heap_util.cpp.s
.PHONY : heap_util.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/main.cpp.s
.PHONY : main.cpp.s

term.o: term.cpp.o

.PHONY : term.o

# target to build an object file
term.cpp.o:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/term.cpp.o
.PHONY : term.cpp.o

term.i: term.cpp.i

.PHONY : term.i

# target to preprocess a source file
term.cpp.i:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/term.cpp.i
.PHONY : term.cpp.i

term.s: term.cpp.s

.PHONY : term.s

# target to generate assembly for a file
term.cpp.s:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/term.cpp.s
.PHONY : term.cpp.s

term_spool.o: term_spool.cpp.o

.PHONY : term_spool.o

# target to build an object file
term_spool.cpp.o:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/term_spool.cpp.o
.PHONY : term_spool.cpp.o

term_spool.i: term_spool.cpp.i

.PHONY : term_spool.i

# target to preprocess a source file
term_spool.cpp.i:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/term_spool.cpp.i
.PHONY : term_spool.cpp.i

term_spool.s: term_spool.cpp.s

.PHONY : term_spool.s

# target to generate assembly for a file
term_spool.cpp.s:
	$(MAKE) -f CMakeFiles/SortNews.dir/build.make CMakeFiles/SortNews.dir/term_spool.cpp.s
.PHONY : term_spool.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... SortNews"
	@echo "... rebuild_cache"
	@echo "... article.o"
	@echo "... article.i"
	@echo "... article.s"
	@echo "... article_spool.o"
	@echo "... article_spool.i"
	@echo "... article_spool.s"
	@echo "... extractTerms/Utility.o"
	@echo "... extractTerms/Utility.i"
	@echo "... extractTerms/Utility.s"
	@echo "... extractTerms/countWord.o"
	@echo "... extractTerms/countWord.i"
	@echo "... extractTerms/countWord.s"
	@echo "... extractTerms/fileOperation.o"
	@echo "... extractTerms/fileOperation.i"
	@echo "... extractTerms/fileOperation.s"
	@echo "... extractTerms/searchTerm.o"
	@echo "... extractTerms/searchTerm.i"
	@echo "... extractTerms/searchTerm.s"
	@echo "... extractTerms/simpleDic.o"
	@echo "... extractTerms/simpleDic.i"
	@echo "... extractTerms/simpleDic.s"
	@echo "... extractTerms/tl_codetbl.o"
	@echo "... extractTerms/tl_codetbl.i"
	@echo "... extractTerms/tl_codetbl.s"
	@echo "... heap_util.o"
	@echo "... heap_util.i"
	@echo "... heap_util.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... term.o"
	@echo "... term.i"
	@echo "... term.s"
	@echo "... term_spool.o"
	@echo "... term_spool.i"
	@echo "... term_spool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

